### ISSUE TITLE
Move this repo to Jakarta EE

### ISSUE THREAD

**Issue by keilw** [jakartaee/nosql#158]
I thought, this repo was already in https://github.com/jakartaee, but it seems it was not moved yet.
We should migrate it as soon as we can.

**Comment by otaviojava** [comment]
@keilw do you know who can do it?

**Comment by keilw** [comment]
Did you ask @ivargrimstad or someone at Eclipse? I assume it needs a Gitlab ticket or one here in Github.

**Comment by ivargrimstad** [comment]
You need to create a GitHub issue since this involves work from webdev. See [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1738) for an example ticket.

**Comment by otaviojava** [comment]
Thanks.
I've created the  issue:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2583

**Comment by Vassopoli** [comment]
Hi everyone!

It seems like this issue can be closed since the [Gitlab issue](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2583) is already closed, and the repo now is at the right place

**Comment by otaviojava** [comment]
Thanks @Vassopoli
